name: Build project and deploy to SmarterASP.NET
on: [push]

jobs:
  build_and_deploy:
    name: Build package and deploy to SmarterASP.NET
    runs-on: windows-latest
    steps:
      - name: build file
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SMARTERASP_SERVER_FTP_SERVER }}
          username: ${{ secrets.SMARTERASP_FTP_USERNAME }}
          password: ${{ secrets.SMARTERASP_FTP_PASSWORD }}
